<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE globalConfig [
    <!ELEMENT globalConfig (defaultDB, passLength, charSet, trials)>
    <!ELEMENT defaultDB (#PCDATA)>
    <!ELEMENT passLength (#PCDATA)>
    <!ELEMENT charSet (#PCDATA)>
    <!ELEMENT trials (#PCDATA)>
    <!ATTLIST charSet
        lowerCase CDATA #REQUIRED
        upperCase CDATA #REQUIRED
        number CDATA #REQUIRED
        space CDATA #REQUIRED
    >
    <!ATTLIST trials deleteAfter CDATA #REQUIRED>
]>

<globalConfig>
    <!--
        デフォルトのデータベース
        コマンド実行時にデータベース名を省略した際に使用します。
    -->
    <defaultDB>SampleDB</defaultDB>

    <!-- 自動生成されるパスワードの長さ -->
    <passLength>16</passLength>

    <!--
        パスワードの自動生成に使用する文字/記号
        charSet要素内に任意の文字/記号を入力すると、それらをパスワード生成に使用します。
        （アルファベット、数字、空白、改行は無視されます。）
    -->
    <charSet lowerCase="true" upperCase="true" number="true" space="false">
        <!-- 例: !#$%@_(){}[] -->
    </charSet>

    <!--
        パスワード入力の試行回数
        試行回数が上限に達した時、データベースを削除するかをdeleteAfter属性（値: true/false）で指定できます。
    -->
    <trials deleteAfter="false">2</trials>
</globalConfig>
