<?xml version="1.0" encoding="UTF-8"?>

<!-- 暗号化されていないSampleDB -->

<!DOCTYPE database [
    <!ELEMENT database (settings, dataset)>

    <!ELEMENT settings (defaultUserName, passLength, charSet)>
    <!ELEMENT defaultUserName (#PCDATA)>
    <!ELEMENT passLength (#PCDATA)>
    <!ELEMENT charSet (#PCDATA)>
    <!ATTLIST charSet
        lowerCase CDATA #REQUIRED
        upperCase CDATA #REQUIRED
        number CDATA #REQUIRED
        symbols CDATA #REQUIRED
        space CDATA #REQUIRED
        custom CDATA #REQUIRED
    >

    <!ELEMENT dataset (data+)>
    <!ELEMENT data (userName, password, message, created, updated)>
    <!ATTLIST data title ID #REQUIRED>
    <!ELEMENT userName (#PCDATA)>
    <!ELEMENT password (value, charSet)>
    <!ELEMENT message (#PCDATA)>
    <!ELEMENT created (#PCDATA)>
    <!ELEMENT updated (#PCDATA)>
    <!ELEMENT value (#PCDATA)>
    <!ATTLIST created
        year CDATA #REQUIRED
        month CDATA #REQUIRED
        date CDATA #REQUIRED
        hours CDATA #REQUIRED
        minutes CDATA #REQUIRED
        seconds CDATA #REQUIRED
    >
    <!ATTLIST updated
        year CDATA #REQUIRED
        month CDATA #REQUIRED
        date CDATA #REQUIRED
        hours CDATA #REQUIRED
        minutes CDATA #REQUIRED
        seconds CDATA #REQUIRED
    >
]>

<database>
    <!-- データ作成時の設定 -->
    <settings>
        <!-- デフォルトのユーザー名 -->
        <defaultUserName>sample@sample.com</defaultUserName>

        <!-- 自動生成されるパスワードの長さ -->
        <passLength>20</passLength>

        <!--
            パスワードの自動生成に使用する文字/記号
            charSet要素内に任意の文字/記号を入力すると、それらをパスワード生成に使用する。
            （アルファベット、数字、空白、改行、および重複する文字は無視される）
        -->
        <charSet lowerCase="true" upperCase="true" number="true" symbols="false" space="false" custom=""/>
    </settings>
    <dataset>
        <data title="Google">
            <userName>sample@sample.com</userName>
            <password>
                <value>sXw3BLNrSUx4OOU6jZOy</value>
                <charSet lowerCase="true" upperCase="true" number="true" symbols="false" space="false" custom=""/>
            </password>
            <message>something</message>
            <created year="2021" month="1" date="1" hours="0" minutes="0" seconds="0" />
            <updated year="2021" month="1" date="1" hours="0" minutes="0" seconds="0" />
        </data>
        <data title="Discord">
            <userName>sample@sample.com</userName>
            <password>
                <value>ECiK1GDGULKTUPFVqp9x</value>
                <charSet lowerCase="true" upperCase="true" number="true" symbols="false" space="false" custom=""/>
            </password>
            <message>something</message>
            <created year="2021" month="2" date="1" hours="0" minutes="0" seconds="0" />
            <updated year="2021" month="2" date="1" hours="0" minutes="0" seconds="0" />
        </data>
        <data title="Twitter">
            <userName>hogehogeman1234</userName>
            <password>
                <value>r79airSs4VG7WrailN8p</value>
                <charSet lowerCase="true" upperCase="true" number="true" symbols="false" space="false" custom=""/>
            </password>
            <message>something</message>
            <created year="2021" month="2" date="2" hours="0" minutes="0" seconds="0" />
            <updated year="2021" month="2" date="2" hours="0" minutes="0" seconds="0" />
        </data>
        <data title="GitHub">
            <userName>hogehogeman1234</userName>
            <password>
                <value>MYfAGIKIP8Co91KQJi7i</value>
                <charSet lowerCase="true" upperCase="true" number="true" symbols="false" space="false" custom=""/>
            </password>
            <message>something</message>
            <created year="2020" month="2" date="2" hours="1" minutes="0" seconds="0" />
            <updated year="2021" month="2" date="2" hours="1" minutes="0" seconds="0" />
        </data>
        <data title="GitLab">
            <userName>hogehogeman1234</userName>
            <password>
                <value>fOsAPh9ktqoOQ1Bjgmz4</value>
                <charSet lowerCase="true" upperCase="true" number="true" symbols="false" space="false" custom=""/>
            </password>
            <message>something</message>
            <created year="2021" month="2" date="2" hours="1" minutes="1" seconds="0" />
            <updated year="2021" month="2" date="2" hours="1" minutes="1" seconds="0" />
        </data>
        <data title="GitBucket">
            <userName>hogehogeman1234</userName>
            <password>
                <value>U4GZAmUVG2sfrdmxiAbE</value>
                <charSet lowerCase="true" upperCase="true" number="true" symbols="false" space="false" custom=""/>
            </password>
            <message>something</message>
            <created year="2021" month="2" date="2" hours="1" minutes="1" seconds="10" />
            <updated year="2021" month="2" date="2" hours="1" minutes="1" seconds="10" />
        </data>
    </dataset>
</database>
